### ISSUE TITLE
License

### ISSUE THREAD

**Issue by aslakhellesoy** [serverless/site#75]
I'm really enjoying the code and the result!

It would be great to know what the license of the code is. For example, would it be ok to fork the repo, tweak the layout and config, and use it to host my own site? Any commercial restrictions?

**Comment by DavidWells** [comment]
Hey @aslakhellesoy fork and go nuts!

Just don't use the design / content =)

🎉

**Comment by mbrukman** [comment]
@DavidWells — can you please clarify (preferably by adding a `LICENSE` file to the repo) what the license is for the repo, and under which license contributions are expected to be?

The trouble is that your earlier response ("fork and go nuts") does not constitute a license, and per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

This means that without an explicit open-source license, the default copyright laws imply "all rights reserved" which means even forking, let alone modifying or distributing, are implicitly disallowed.

Adding an explicit license to the repo would address these types of issues.

For example, https://github.com/serverless/guide#license says:

> ## License
> 
> <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

If that's the same for this repo, please annotate it similarly so that it's clear.

Thanks!
